import { ChakraProvider } from "@chakra-ui/react";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import "./Styles/custom.scss";
import Image from "next/image";

const font = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ChakraProvider cssVarsRoot="body">
          {children}
          <div className="Whatsapp-container">
            <a
              href="http://wa.me/+5492615520011"
              target="blanket"
              className="whatsapp-icon"
            >
              <Image
                className="img-Whatsapp"
                src="/Whatsapp-icon.png"
                alt=""
                width={50}
                height={50}
              />
            </a>
          </div>
        </ChakraProvider>
      </body>
    </html>
  );
}
